################################################################################
# title
################################################################################
#
# Juan Carlos Villaseñor-Derbez
# jc_villasenor@miami.edu
# August 1, 2025
#
# This script combines the raw port data created by Emma and the conapesca
# port data created by myself to build the final version of our data
#
################################################################################

## SET UP ######################################################################

# Load packages ----------------------------------------------------------------
pacman::p_load(
  here,
  sf,
  tidyverse
)

# Load data --------------------------------------------------------------------
mex_ports_raw <- read_csv(here("data/raw/mexican_ports.csv"))                   # These data were generated by hand by Emma. See README for details.
dictionary <- read_csv(here("data/raw/mex_ports_dictionary.csv"))               # These data were generated by hand by Emma. See README for details.

## PROCESSING ##################################################################

# Retain relevant columns from the dictionary ----------------------------------
dictionary_clean <- dictionary |> 
  select(landing_site_key, port_id) |> 
  distinct() |> 
  drop_na()

# Build the final version of the mexican ports data set ------------------------
mex_ports <- mex_ports_raw |> 
  # Remove inland ports (they are lake ports)
  filter(!port_id %in% c("14004", # remove port AJIJIC in Chapala lake
                         "14003", # remove port CHAPALA in Chapala lake
                         "16003", # remove port ZIRAHUEN in Lago de Zirahuén
                         "16002"  # remove LAGO DE APATZCUARO in Patzcuaro lake
  )
  ) |>
  # Remove some rows that are NA across the board
  drop_na() |> 
  # Add landing site key to match with CONAPESCA
  left_join(dictionary_clean, by = join_by("port_id")) |> 
  # Rename and reorder columns
  select(municipality_id = municipality_code,
         municipality_name,
         port_id,
         port_name,
         landing_site_id = landing_site_key,
         longitude,
         latitude)

mex_ports_sf <- st_as_sf(mex_ports,
                         coords = c("longitude", "latitude"),
                         crs = "EPSG:4326")


## EXPORT ######################################################################

# Tabular versions of the data -------------------------------------------------
write_rds(x = mex_ports,
          file = here("data", "clean", "mex_ports.rds"))
write_csv(x = mex_ports,
          file = here("data", "clean", "mex_ports.csv"))

# Geospatial version of the data -----------------------------------------------
st_write(obj = mex_ports_sf,
         dsn = here("data", "clean", "mex_ports.gpkg"),
         delete_dsn = TRUE)

